version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 Important line!
volumes:
  jenkins_home:
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock  # ✅ Allows Jenkins to use host Docker

