version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    build:
      context: .
      dockerfile: Dockerfile.jenkins  # If you're using a custom Dockerfile for Jenkins
    ports:
      - "8087:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker-in-Docker access

  docker:
    image: docker:19.03.12-dind  # Docker-in-Docker image
    privileged: true  # Required for Docker-in-Docker to function properly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
